### ISSUE TITLE
boot loops while flashing occurring when entering 'Writing flash' on both rm & xfw 

### ISSUE THREAD

**Issue by jbohack** [ESurge/flipperzero-namechanger#1]
A few people have been having issues with flashing and I was able to narrow it down to this plugin. After removing it from my XFW build, boot loops no longer seem present. I'll investigate some of the issues with the namechanger program and attempt a fix and send you a PR if I get any fixes however currently the cause is unknown.

The crash upon a 'successful build' is a NULL_pointer_dereference error.

**Comment by ESurge** [comment]
Hi, thanks for the heads up.

I've seen this happen in recent days and I believe something has changed in furi_hal_version.c

Regardless, I've been planning on cleaning up the code a bit, and I believe I have fixed the boot loop issue.

More testing is required before I push the updates, but when I do, it'll also be pushed to RM firmware.

**Comment by ESurge** [comment]
Pushed new code. This boot loop shouldn't occur anymore or at least I wasn't able to reproduce it. I tested 5 - 6 times going between different firmware.
